name: Build Production Assets

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, '[ci-skip]')"

    steps:
    - uses: actions/checkout@v1

    - name: Use Node.js
      uses: actions/setup-node@v1

    - name: npm install
      run: npm install
    
    - name: npm run prod
      run: npm run prod
    
    - name: Commit files and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_REPO_SECRET }}
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
        git checkout master
        git add .
        git diff --quiet && git diff --staged --quiet || (git commit -am "Build production assets (Github Actions) [ci-skip]"; git push origin master)
